---
services:
  - name: NetworkManager
    mandatory: false
  - name: lightdm
    mandatory: false
  - name: nftables
    mandatory: false
  - name: apparmor
    mandatory: false
  - name: zramswap
    mandatory: false
  - name: unattended-upgrades
    mandatory: false
  - name: kiyu-firstboot
    mandatory: false
timers:
  - name: fstrim
    mandatory: false
