---
defaultGroups:
  - name: users
    must: true
  - name: sudo
    must: true
  - cdrom
  - audio
  - video
  - plugdev
  - netdev
  - dip
  - bluetooth
  - lpadmin
  - scanner
autologinGroup: autologin
sudoersGroup: sudo
setRootPassword: false
doAutologin: false
userShell: /bin/bash
allowWeakPasswords: true
allowWeakPasswordsDefault: false
passwordRequirements:
  minLength: 6
  maxLength: -1
